# Config file for which alerts to associate with each fridge


alerts:
  PulseTubeOff:  # requires modern bluefors software with status file
    - venus

  MxcAbove1K:
    - queenie
    - scarlett
    - tallulah
    - venus
    - winona

  UnresponsiveFridge:
    - queenie
    - scarlett
    - tallulah
    - venus
    - winona

  HotOilTemp:
    - queenie
    - scarlett
    - tallulah
    - venus
    - winona

  LosingVacuum:
    - queenie
    - scarlett
    - tallulah
    - venus
    - winona

  # MagnetQuench:
  #   - queenie
  #   - scarlett
  #   - tallulah
  #   - venus
  #   - winona
