# Config file for which alerts to associate with each fridge


alerts:
  PulseTubeAlert:  # requires modern bluefors software
    - venus

  MxcAbove1K:
    - queenie
    - scarlett
    - tallulah
    - venus
    - winona

  #OilTempAlert:
    #- venus